"""Addd ondelete CASCADE to sessionID in transcripts

Revision ID: 04c4443b2eff
Revises: 5257dd2da615
Create Date: 2024-03-04 21:10:19.999318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04c4443b2eff'
down_revision: Union[str, None] = '5257dd2da615'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_transcript_chat_session', 'transcripts', type_='foreignkey')
    op.drop_constraint('transcripts_sessionID_fkey', 'transcripts', type_='foreignkey')
    op.create_foreign_key(None, 'transcripts', 'chat_sessions', ['sessionID'], ['id'], ondelete='CASCADE')
    op.drop_column('transcripts', 'chat_session_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transcripts', sa.Column('chat_session_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'transcripts', type_='foreignkey')
    op.create_foreign_key('transcripts_sessionID_fkey', 'transcripts', 'chat_sessions', ['sessionID'], ['id'])
    op.create_foreign_key('fk_transcript_chat_session', 'transcripts', 'chat_sessions', ['chat_session_id'], ['id'], ondelete='CASCADE')
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('srid > 0 AND srid <= 998999', name='spatial_ref_sys_srid_check'),
    sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    )
    # ### end Alembic commands ###
