"""trnascripts and chat sessions cascade removed, transcripts table added

Revision ID: 088abe0353be
Revises: 046b456f5b3f
Create Date: 2024-03-04 12:19:30.662042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '088abe0353be'
down_revision: Union[str, None] = '046b456f5b3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transcripts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('transcriptID', sa.String(), nullable=True),
    sa.Column('sessionID', sa.UUID(), nullable=False),
    sa.Column('userID', sa.UUID(), nullable=True),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('last_modified', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['sessionID'], ['chat_sessions.id'], ),
    sa.ForeignKeyConstraint(['userID'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transcripts_id'), 'transcripts', ['id'], unique=False)
    op.create_index(op.f('ix_transcripts_transcriptID'), 'transcripts', ['transcriptID'], unique=True)
    op.add_column('chat_sessions', sa.Column('userID', sa.UUID(), nullable=True))
    op.add_column('chat_sessions', sa.Column('assistantID', sa.UUID(), nullable=True))
    op.drop_constraint('chat_sessions_Assistant_fkey', 'chat_sessions', type_='foreignkey')
    op.drop_constraint('chat_sessions_User_fkey', 'chat_sessions', type_='foreignkey')
    op.create_foreign_key(None, 'chat_sessions', 'assistants', ['assistantID'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'chat_sessions', 'users', ['userID'], ['id'], ondelete='SET NULL')
    op.drop_column('chat_sessions', 'Assistant')
    op.drop_column('chat_sessions', 'User')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_sessions', sa.Column('User', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('chat_sessions', sa.Column('Assistant', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'chat_sessions', type_='foreignkey')
    op.drop_constraint(None, 'chat_sessions', type_='foreignkey')
    op.create_foreign_key('chat_sessions_User_fkey', 'chat_sessions', 'users', ['User'], ['id'])
    op.create_foreign_key('chat_sessions_Assistant_fkey', 'chat_sessions', 'assistants', ['Assistant'], ['id'])
    op.drop_column('chat_sessions', 'assistantID')
    op.drop_column('chat_sessions', 'userID')
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('srid > 0 AND srid <= 998999', name='spatial_ref_sys_srid_check'),
    sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    )
    op.drop_index(op.f('ix_transcripts_transcriptID'), table_name='transcripts')
    op.drop_index(op.f('ix_transcripts_id'), table_name='transcripts')
    op.drop_table('transcripts')
    # ### end Alembic commands ###
