"""Add cascade delete on documents and agents on Module delete

Revision ID: 0eb9a76b158d
Revises: b19956b94f0f
Create Date: 2024-07-02 12:17:56.314633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0eb9a76b158d'
down_revision: Union[str, None] = 'b19956b94f0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('agent_module_module_id_fkey', 'agent_module', type_='foreignkey')
    op.drop_constraint('agent_module_agent_id_fkey', 'agent_module', type_='foreignkey')
    op.create_foreign_key(None, 'agent_module', 'agents', ['agent_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'agent_module', 'modules', ['module_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('document_module_module_id_fkey', 'document_module', type_='foreignkey')
    op.drop_constraint('document_module_document_id_fkey', 'document_module', type_='foreignkey')
    op.create_foreign_key(None, 'document_module', 'documents', ['document_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'document_module', 'modules', ['module_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'document_module', type_='foreignkey')
    op.drop_constraint(None, 'document_module', type_='foreignkey')
    op.create_foreign_key('document_module_document_id_fkey', 'document_module', 'documents', ['document_id'], ['id'])
    op.create_foreign_key('document_module_module_id_fkey', 'document_module', 'modules', ['module_id'], ['id'])
    op.drop_constraint(None, 'agent_module', type_='foreignkey')
    op.drop_constraint(None, 'agent_module', type_='foreignkey')
    op.create_foreign_key('agent_module_agent_id_fkey', 'agent_module', 'agents', ['agent_id'], ['id'])
    op.create_foreign_key('agent_module_module_id_fkey', 'agent_module', 'modules', ['module_id'], ['id'])
    # ### end Alembic commands ###
