"""modified assistant_document relationship and table

Revision ID: 1d5cc089f022
Revises: 06563ff5e4f0
Create Date: 2024-05-10 09:21:50.581671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d5cc089f022'
down_revision: Union[str, None] = '06563ff5e4f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assistant_document',
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('assistant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['assistant_id'], ['assistants.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('document_id', 'assistant_id')
    )
    op.drop_table('assistant_file')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assistant_file',
    sa.Column('document_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('assistant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['assistant_id'], ['assistants.id'], name='assistant_file_assistant_id_fkey'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name='assistant_file_document_id_fkey'),
    sa.PrimaryKeyConstraint('document_id', 'assistant_id', name='assistant_file_pkey')
    )
    op.drop_table('assistant_document')
    # ### end Alembic commands ###
