"""add thread and last_agent  to chatsession table and create agent_chat many-to-many relationship

Revision ID: 23c07e6d7f76
Revises: be4173d49fe4
Create Date: 2024-07-06 23:26:44.973940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23c07e6d7f76'
down_revision: Union[str, None] = 'be4173d49fe4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_chat',
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('chat_session_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['chat_session_id'], ['chat_sessions.id'], ),
    sa.PrimaryKeyConstraint('agent_id', 'chat_session_id')
    )
    op.add_column('chat_sessions', sa.Column('threadID', sa.String(length=40), nullable=False))
    op.add_column('chat_sessions', sa.Column('last_agent', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_chat_sessions_threadID'), 'chat_sessions', ['threadID'], unique=False)
    op.create_foreign_key(None, 'chat_sessions', 'agents', ['last_agent'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chat_sessions', type_='foreignkey')
    op.drop_index(op.f('ix_chat_sessions_threadID'), table_name='chat_sessions')
    op.drop_column('chat_sessions', 'last_agent')
    op.drop_column('chat_sessions', 'threadID')
    op.drop_table('agent_chat')
    # ### end Alembic commands ###
