"""Add summarizer and analytic columns to agent

Revision ID: 307d67efd8fd
Revises: d14d2faed72f
Create Date: 2024-07-12 13:46:15.809565

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '307d67efd8fd'
down_revision: Union[str, None] = 'd14d2faed72f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('summarizer', sa.Boolean(), nullable=True))
    op.add_column('agents', sa.Column('analytic', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agents', 'analytic')
    op.drop_column('agents', 'summarizer')
    # ### end Alembic commands ###
