"""removed file column and roles relationship  from documents table

Revision ID: 402e4ecaaef9
Revises: 04c4443b2eff
Create Date: 2024-03-19 21:37:24.900446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '402e4ecaaef9'
down_revision: Union[str, None] = '04c4443b2eff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'agent_file', 'documents', ['document_id'], ['id'])
    op.create_foreign_key(None, 'document_roles', 'documents', ['document_id'], ['id'])
    op.drop_column('documents', 'file')
    op.drop_table('document_roles')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('file', postgresql.BYTEA(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'document_roles', type_='foreignkey')
    op.drop_constraint(None, 'agent_file', type_='foreignkey')
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('srid > 0 AND srid <= 998999', name='spatial_ref_sys_srid_check'),
    sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    )
    # ### end Alembic commands ###
