"""add created and last_modified to agents and documents tables

Revision ID: 419c11f635ca
Revises: 402e4ecaaef9
Create Date: 2024-03-20 16:24:53.720714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '419c11f635ca'
down_revision: Union[str, None] = '402e4ecaaef9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('created', sa.DateTime(), nullable=True))
    op.add_column('agents', sa.Column('last_modified', sa.DateTime(), nullable=True))
    op.add_column('documents', sa.Column('created', sa.DateTime(), nullable=True))
    op.add_column('documents', sa.Column('last_modified', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'last_modified')
    op.drop_column('documents', 'created')
    op.drop_column('agents', 'last_modified')
    op.drop_column('agents', 'created')
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('srid > 0 AND srid <= 998999', name='spatial_ref_sys_srid_check'),
    sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    )
    op.drop_table('document_roles')
    # ### end Alembic commands ###
