"""Update Module table (desc, flow, chaining, voice, analytics, summaries)

Revision ID: 723c67840689
Revises: 0eb9a76b158d
Create Date: 2024-07-02 12:47:13.518787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '723c67840689'
down_revision: Union[str, None] = '0eb9a76b158d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('modules', sa.Column('description', sa.String(length=200), nullable=True))
    op.add_column('modules', sa.Column('flow_control', sa.String(length=10), nullable=True))
    op.add_column('modules', sa.Column('prompt_chaining', sa.Boolean(), nullable=True))
    op.add_column('modules', sa.Column('voice', sa.Boolean(), nullable=True))
    op.add_column('modules', sa.Column('convo_analytics', sa.Boolean(), nullable=True))
    op.add_column('modules', sa.Column('summaries', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_modules_description'), 'modules', ['description'], unique=False)
    op.create_index(op.f('ix_modules_flow_control'), 'modules', ['flow_control'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_modules_flow_control'), table_name='modules')
    op.drop_index(op.f('ix_modules_description'), table_name='modules')
    op.drop_column('modules', 'summaries')
    op.drop_column('modules', 'convo_analytics')
    op.drop_column('modules', 'voice')
    op.drop_column('modules', 'prompt_chaining')
    op.drop_column('modules', 'flow_control')
    op.drop_column('modules', 'description')
    # ### end Alembic commands ###
