"""Add fileType column to Document table

Revision ID: 7f0fa7e01adc
Revises: a5e2cd45a5fa
Create Date: 2024-07-29 17:30:04.818742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f0fa7e01adc'
down_revision: Union[str, None] = 'a5e2cd45a5fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('fileType', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'fileType')
    # ### end Alembic commands ###
