"""revert modification assistant_document relationship and table

Revision ID: 8254193e3a91
Revises: 1d5cc089f022
Create Date: 2024-05-10 09:36:02.543062

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8254193e3a91'
down_revision: Union[str, None] = '1d5cc089f022'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
