"""Add extracted_imgs to documents table and create extracted_images table

Revision ID: 8617cc48b2ff
Revises: 4c3de3af733f
Create Date: 2024-08-07 17:25:10.938759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8617cc48b2ff'
down_revision: Union[str, None] = '4c3de3af733f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('extracted_images',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('file_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extracted_images_id'), 'extracted_images', ['id'], unique=False)
    op.add_column('documents', sa.Column('content_hash', sa.String(length=64), nullable=True))
    op.create_unique_constraint(None, 'documents', ['content_hash'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'documents', type_='unique')
    op.drop_column('documents', 'content_hash')
    op.drop_index(op.f('ix_extracted_images_id'), table_name='extracted_images')
    op.drop_table('extracted_images')
    # ### end Alembic commands ###
