"""Add summary and analysis columns to chatsession

Revision ID: 886c16bd51f2
Revises: 307d67efd8fd
Create Date: 2024-07-12 14:52:17.936996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '886c16bd51f2'
down_revision: Union[str, None] = '307d67efd8fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_sessions', sa.Column('summary', sa.String(), nullable=True))
    op.add_column('chat_sessions', sa.Column('analysis', sa.String(), nullable=True))
    op.create_index(op.f('ix_chat_sessions_analysis'), 'chat_sessions', ['analysis'], unique=False)
    op.create_index(op.f('ix_chat_sessions_summary'), 'chat_sessions', ['summary'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_sessions_summary'), table_name='chat_sessions')
    op.drop_index(op.f('ix_chat_sessions_analysis'), table_name='chat_sessions')
    op.drop_column('chat_sessions', 'analysis')
    op.drop_column('chat_sessions', 'summary')
    # ### end Alembic commands ###
