"""add director and prompt_chaining columns to agent, remove prompt_chaining from module

Revision ID: a14276e1e36c
Revises: f44f84e6a3a1
Create Date: 2024-07-04 11:03:17.105144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a14276e1e36c'
down_revision: Union[str, None] = 'f44f84e6a3a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('wrapper_prompt', sa.String(), nullable=True))
    op.add_column('agents', sa.Column('prompt_chaining', sa.Boolean(), nullable=True))
    op.drop_column('modules', 'prompt_chaining')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('modules', sa.Column('prompt_chaining', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('agents', 'prompt_chaining')
    op.drop_column('agents', 'wrapper_prompt')
    # ### end Alembic commands ###
