"""add columns initial_prompt and agent_id_pointer to agent table

Revision ID: be4173d49fe4
Revises: a14276e1e36c
Create Date: 2024-07-05 13:46:02.833665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be4173d49fe4'
down_revision: Union[str, None] = 'a14276e1e36c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('initial_prompt', sa.String(), nullable=True))
    op.add_column('agents', sa.Column('agent_id_pointer', sa.UUID(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agents', 'agent_id_pointer')
    op.drop_column('agents', 'initial_prompt')
    # ### end Alembic commands ###
