"""change threadID column length on chatsession to 150

Revision ID: d14d2faed72f
Revises: 23c07e6d7f76
Create Date: 2024-07-07 01:21:54.859638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd14d2faed72f'
down_revision: Union[str, None] = '23c07e6d7f76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chat_sessions', 'threadID',
               existing_type=sa.VARCHAR(length=40),
               type_=sa.String(length=150),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chat_sessions', 'threadID',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=40),
               existing_nullable=False)
    # ### end Alembic commands ###
