"""init

Revision ID: e234b2246dfc
Revises: 
Create Date: 2024-02-25 14:34:29.344794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e234b2246dfc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'document_roles', 'documents', ['document_id'], ['id'])
    op.add_column('transcripts', sa.Column('ChatSession', sa.UUID(), nullable=False))
    op.add_column('transcripts', sa.Column('created', sa.DateTime(), nullable=True))
    op.add_column('transcripts', sa.Column('last_modified', sa.DateTime(), nullable=True))
    op.drop_index('ix_transcripts_sessionID', table_name='transcripts')
    op.create_foreign_key(None, 'transcripts', 'chat_sessions', ['ChatSession'], ['id'])
    op.drop_column('transcripts', 'sessionID')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transcripts', sa.Column('sessionID', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'transcripts', type_='foreignkey')
    op.create_index('ix_transcripts_sessionID', 'transcripts', ['sessionID'], unique=True)
    op.drop_column('transcripts', 'last_modified')
    op.drop_column('transcripts', 'created')
    op.drop_column('transcripts', 'ChatSession')
    op.drop_constraint(None, 'document_roles', type_='foreignkey')
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('srid > 0 AND srid <= 998999', name='spatial_ref_sys_srid_check'),
    sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    )
    # ### end Alembic commands ###
