"""remove cascade from document-assistant relationship

Revision ID: eef99e5c0b26
Revises: 8254193e3a91
Create Date: 2024-05-10 09:46:39.112708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eef99e5c0b26'
down_revision: Union[str, None] = '8254193e3a91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
