"""add director column to agent

Revision ID: f44f84e6a3a1
Revises: 8c3e41d82983
Create Date: 2024-07-04 10:49:13.433803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f44f84e6a3a1'
down_revision: Union[str, None] = '8c3e41d82983'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('director', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agents', 'director')
    # ### end Alembic commands ###
