"""Add messages_len column to chatsession

Revision ID: fbc9dd358d99
Revises: 886c16bd51f2
Create Date: 2024-07-15 12:14:45.276721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbc9dd358d99'
down_revision: Union[str, None] = '886c16bd51f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_sessions', sa.Column('messages_len', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_sessions', 'messages_len')
    # ### end Alembic commands ###
